library(extRemes)
library(DESeq2)
library(tidyverse)
library(airway)
library("EnrichmentBrowser")
library(ssizeRNA)
library("lme4")
library("mvtnorm")
library("GSVA")
library(tibble)
library("SummarizedExperiment")
library("limma")
library("edgeR")
library(optimx)
# is not installed on lugh
library("GSAR")
library("MASS")
library("lcmm")
library(pracma)
library(invgamma)
#library(ggplot2)
#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")

#BiocManager::install("GSAR")